import { NextResponse } from 'next/server';
import { FirestoreService } from '@/lib/services/firestore-service';
import { Product, TrendCategory, ViabilityGrade } from '@/types/product';

export async function POST() {
  try {
    const db = new FirestoreService();

    // Sample trending products data
    const sampleProducts: Product[] = [
      {
        id: 'demo-product-001',
        title: 'Viral LED Light Strips - 16.4ft RGB Color Changing Lights',
        image_url: 'https://via.placeholder.com/400x400?text=LED+Light+Strips',
        current_price: 19.99,
        original_price: 39.99,
        sold_count: 15420,
        rating: 4.8,
        review_count: 3241,
        category: 'Home & Garden',
        shop_name: 'TechLife Store',
        shop_id: 'techlife_official',
        product_url: 'https://www.tiktok.com/@techlife/product/demo-001',
        shop_url: 'https://www.tiktok.com/@techlife',
        in_stock: true,
        trend_score: 92.5,
        trend_category: TrendCategory.BREAKOUT,
        orders_3d_delta: 2341,
        orders_7d_delta: 5120,
        price_discount_rate: 0.50,
        reviews_3d_delta: 142,
        velocity_3d: 780,
        acceleration: 2.4,
        confidence_score: 0.89,
        viability_grade: ViabilityGrade.A,
        pv_demand_momentum: 95,
        pv_sustained_interest: 88,
        pv_price_stability: 75,
        pv_saturation: 80,
        pv_sentiment: 92,
        viability_summary: 'Exceptional breakout product with strong viral momentum and sustainable demand.',
        has_affiliate_program: true,
        commission_rate: 0.12,
        first_seen: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
        last_updated: new Date().toISOString(),
        snapshot_count: 21,
      },
      {
        id: 'demo-product-002',
        title: 'Portable Blender - USB Rechargeable Mini Smoothie Maker',
        image_url: 'https://via.placeholder.com/400x400?text=Portable+Blender',
        current_price: 24.99,
        original_price: 49.99,
        sold_count: 28540,
        rating: 4.7,
        review_count: 5821,
        category: 'Kitchen & Dining',
        shop_name: 'HomeEssentials',
        shop_id: 'homeessentials_shop',
        product_url: 'https://www.tiktok.com/@homeessentials/product/demo-002',
        shop_url: 'https://www.tiktok.com/@homeessentials',
        in_stock: true,
        trend_score: 88.3,
        trend_category: TrendCategory.SUSTAINED,
        orders_3d_delta: 1240,
        orders_7d_delta: 3890,
        price_discount_rate: 0.50,
        reviews_3d_delta: 98,
        velocity_3d: 413,
        acceleration: 1.2,
        confidence_score: 0.92,
        viability_grade: ViabilityGrade.A_MINUS,
        pv_demand_momentum: 85,
        pv_sustained_interest: 95,
        pv_price_stability: 82,
        pv_saturation: 65,
        pv_sentiment: 90,
        viability_summary: 'Proven winner with consistent sales and strong customer satisfaction.',
        has_affiliate_program: true,
        commission_rate: 0.15,
        first_seen: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
        last_updated: new Date().toISOString(),
        snapshot_count: 84,
      },
      {
        id: 'demo-product-003',
        title: 'Makeup Brush Set - 20 Piece Professional Cosmetic Tools',
        image_url: 'https://via.placeholder.com/400x400?text=Makeup+Brush+Set',
        current_price: 15.99,
        original_price: 15.99,
        sold_count: 42180,
        rating: 4.9,
        review_count: 8934,
        category: 'Beauty & Personal Care',
        shop_name: 'BeautyHub',
        shop_id: 'beautyhub_official',
        product_url: 'https://www.tiktok.com/@beautyhub/product/demo-003',
        shop_url: 'https://www.tiktok.com/@beautyhub',
        in_stock: true,
        trend_score: 85.7,
        trend_category: TrendCategory.SUSTAINED,
        orders_3d_delta: 890,
        orders_7d_delta: 2840,
        price_discount_rate: 0.0,
        reviews_3d_delta: 156,
        velocity_3d: 297,
        acceleration: 1.1,
        confidence_score: 0.94,
        viability_grade: ViabilityGrade.B_PLUS,
        pv_demand_momentum: 80,
        pv_sustained_interest: 92,
        pv_price_stability: 95,
        pv_saturation: 55,
        pv_sentiment: 95,
        viability_summary: 'Reliable performer with excellent reviews and steady growth.',
        has_affiliate_program: true,
        commission_rate: 0.10,
        first_seen: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        last_updated: new Date().toISOString(),
        snapshot_count: 135,
      },
      {
        id: 'demo-product-004',
        title: 'Wireless Earbuds - Bluetooth 5.3 Noise Cancelling',
        image_url: 'https://via.placeholder.com/400x400?text=Wireless+Earbuds',
        current_price: 29.99,
        original_price: 79.99,
        sold_count: 8420,
        rating: 4.6,
        review_count: 1842,
        category: 'Electronics',
        shop_name: 'AudioPro',
        shop_id: 'audiopro_store',
        product_url: 'https://www.tiktok.com/@audiopro/product/demo-004',
        shop_url: 'https://www.tiktok.com/@audiopro',
        in_stock: true,
        trend_score: 78.4,
        trend_category: TrendCategory.DISCOUNT_DRIVEN,
        orders_3d_delta: 1580,
        orders_7d_delta: 4120,
        price_discount_rate: 0.625,
        reviews_3d_delta: 89,
        velocity_3d: 527,
        acceleration: 1.8,
        confidence_score: 0.76,
        viability_grade: ViabilityGrade.B,
        pv_demand_momentum: 75,
        pv_sustained_interest: 65,
        pv_price_stability: 60,
        pv_saturation: 70,
        pv_sentiment: 85,
        viability_summary: 'Strong discount-driven sales but monitor for sustainability post-promotion.',
        has_affiliate_program: true,
        commission_rate: 0.08,
        first_seen: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        last_updated: new Date().toISOString(),
        snapshot_count: 42,
      },
      {
        id: 'demo-product-005',
        title: 'Ice Roller for Face - Skin Care Massager Tool',
        image_url: 'https://via.placeholder.com/400x400?text=Ice+Roller',
        current_price: 12.99,
        original_price: 12.99,
        sold_count: 34620,
        rating: 4.8,
        review_count: 6234,
        category: 'Beauty & Personal Care',
        shop_name: 'SkinCare Plus',
        shop_id: 'skincare_plus',
        product_url: 'https://www.tiktok.com/@skincare/product/demo-005',
        shop_url: 'https://www.tiktok.com/@skincare',
        in_stock: true,
        trend_score: 91.2,
        trend_category: TrendCategory.BREAKOUT,
        orders_3d_delta: 2840,
        orders_7d_delta: 8120,
        price_discount_rate: 0.0,
        reviews_3d_delta: 234,
        velocity_3d: 947,
        acceleration: 2.8,
        confidence_score: 0.88,
        viability_grade: ViabilityGrade.A,
        pv_demand_momentum: 96,
        pv_sustained_interest: 85,
        pv_price_stability: 98,
        pv_saturation: 75,
        pv_sentiment: 92,
        viability_summary: 'Viral trending product with explosive growth and organic pricing power.',
        has_affiliate_program: true,
        commission_rate: 0.18,
        first_seen: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
        last_updated: new Date().toISOString(),
        snapshot_count: 63,
      },
    ];

    // Save all products
    for (const product of sampleProducts) {
      await db.saveProduct(product);

      // Create initial snapshot
      await db.saveSnapshot(product.id, {
        timestamp: product.last_updated,
        price: product.current_price,
        sold_count: product.sold_count,
        review_count: product.review_count,
        rating: product.rating,
        in_stock: product.in_stock,
      });
    }

    return NextResponse.json({
      message: 'Successfully seeded database with demo products',
      count: sampleProducts.length,
      products: sampleProducts.map(p => ({
        id: p.id,
        title: p.title,
        trend_score: p.trend_score,
        viability_grade: p.viability_grade,
      })),
    });
  } catch (error) {
    console.error('Error seeding database:', error);
    return NextResponse.json(
      { error: 'Failed to seed database', details: String(error) },
      { status: 500 }
    );
  }
}

export async function GET() {
  return NextResponse.json({
    message: 'TokSpotter Database Seeder',
    usage: 'Send POST request to seed database with demo products',
    note: 'This will create 5 sample trending products for testing',
  });
}
